// Re-export all Rust-generated types (these are the source of truth for Spotify API shapes)
export type {
  SpotifyImage,
  Followers,
  SpotifyUserProfile,
  SpotifyOwner,
  PlaylistTracksRef,
  SpotifyPlaylist,
  SpotifyPlaylists,
  SpotifyArtistBrief,
  SpotifyAlbumBrief,
  SpotifyTrack,
  PlaylistTrackItem,
  PlaylistTracks,
  PlaylistDetailTracks,
  PlaylistDetail,
  SpotifyAlbum,
  AlbumTracks,
  SpotifyArtist,
  ArtistAlbums,
  LikedTrackItem,
  LikedTracks,
  SearchTracks,
  SearchArtists,
  SearchAlbums,
  SearchPlaylists,
  SearchResult,
  Recommendations,
  ArtistTopTracks,
  ArtistRelatedArtists,
  Device,
  CurrentlyPlaying,
  SpotifyTrackWrapper,
  TopArtists,
  TopTracks,
  PlayHistory,
  RecentlyPlayed,
  SpotifyShowPage,
  SpotifyShow,
  ShowEpisode,
  ShowEpisodesPage,
  RepeatMode,
  PlaybackState,
  ModManifest,
  ModType,
  ModEntry,
} from './types.generated';

// Hand-maintained types that have NO Rust counterpart
export type SearchType = 'track' | 'artist' | 'album' | 'playlist';
