/*
 Generated by typeshare 1.13.4
*/

export interface SpotifyArtistBrief {
  id?: string;
  name?: string;
  uri?: string;
}

export interface SpotifyImage {
  url?: string;
  height?: number;
  width?: number;
}

export interface SpotifyAlbumBrief {
  id?: string;
  name?: string;
  images: SpotifyImage[];
  uri?: string;
  release_date?: string;
}

export interface SpotifyTrack {
  id?: string;
  name?: string;
  uri?: string;
  duration_ms?: number;
  artists?: SpotifyArtistBrief[];
  album?: SpotifyAlbumBrief;
  disc_number?: number;
  track_number?: number;
  explicit?: boolean;
  type: string;
}

export interface AlbumTracks {
  items: SpotifyTrack[];
  total: number;
  offset: number;
  limit: number;
  next?: string;
}

export interface ArtistAlbums {
  items: SpotifyAlbumBrief[];
  total: number;
  offset: number;
  limit: number;
  next?: string;
}

export interface Followers {
  total: number;
}

export interface SpotifyArtist {
  id?: string;
  name?: string;
  images: SpotifyImage[];
  genres?: string[];
  popularity?: number;
  followers?: Followers;
  uri?: string;
  type: string;
}

export interface ArtistRelatedArtists {
  artists: SpotifyArtist[];
}

export interface ArtistTopTracks {
  tracks: SpotifyTrack[];
}

export interface SpotifyTrackWrapper {
  id?: string;
  name: string;
  uri: string;
  duration_ms: number;
  artists: SpotifyArtistBrief[];
  album?: SpotifyAlbumBrief;
  type: string;
}

export interface Device {
  id: string;
  name: string;
  is_active: boolean;
  volume_percent?: number;
}

export interface CurrentlyPlaying {
  item?: SpotifyTrackWrapper;
  is_playing: boolean;
  progress_ms?: number;
  device?: Device;
}

export interface LikedTrackItem {
  added_at: string;
  track: SpotifyTrack;
}

export interface LikedTracks {
  items: LikedTrackItem[];
  total: number;
  offset: number;
  limit: number;
  next?: string;
}

export enum ModType {
  Theme = 'theme',
  Extension = 'extension',
  App = 'app',
}

export interface ModEntry {
  path: string;
  name: string;
  version: string;
  mod_type: ModType;
  entry: string;
  description?: string;
  author?: string;
  litetify_api_version: string;
  permissions: string[];
  icon: string;
  error?: string;
}

export interface ModManifest {
  name: string;
  version: string;
  type: ModType;
  entry: string;
  description?: string;
  author?: string;
  litetifyApiVersion: string;
  permissions?: string[];
  icon?: string;
}

export interface PlayHistory {
  track: SpotifyTrack;
  played_at: string;
}

export enum RepeatMode {
  Off = 'Off',
  Context = 'Context',
  Track = 'Track',
}

export interface PlaybackState {
  uri?: string;
  track_id?: string;
  name?: string;
  artist?: string;
  album?: string;
  album_image?: string;
  duration_ms: number;
  position_ms: number;
  is_playing: boolean;
  volume: number;
  shuffle: boolean;
  repeat: RepeatMode;
  device_id?: string;
}

export interface SpotifyOwner {
  id?: string;
  display_name?: string;
}

export interface PlaylistTrackItem {
  added_at?: string;
  track?: SpotifyTrack;
}

export interface PlaylistDetailTracks {
  items?: PlaylistTrackItem[];
  total: number;
  offset?: number;
  limit?: number;
  next?: string;
}

export interface PlaylistDetail {
  id?: string;
  name?: string;
  description?: string;
  images: SpotifyImage[];
  owner: SpotifyOwner;
  public?: boolean;
  followers?: Followers;
  tracks?: PlaylistDetailTracks;
  type: string;
}

export interface PlaylistTracks {
  items?: PlaylistTrackItem[];
  total: number;
  offset?: number;
  limit?: number;
  next?: string;
}

export interface PlaylistTracksRef {
  total?: number;
  href?: string;
}

export interface RecentlyPlayed {
  items: PlayHistory[];
}

export interface Recommendations {
  tracks: SpotifyTrack[];
}

export interface SpotifyAlbum {
  id?: string;
  name?: string;
  artists?: SpotifyArtistBrief[];
  images: SpotifyImage[];
  tracks?: AlbumTracks;
  uri?: string;
  release_date?: string;
  total_tracks: number;
  label?: string;
  popularity?: number;
  genres?: string[];
  type: string;
}

export interface SearchAlbums {
  items?: SpotifyAlbum[];
  total: number;
}

export interface SearchArtists {
  items?: SpotifyArtist[];
  total: number;
}

export interface SpotifyPlaylist {
  id?: string;
  name?: string;
  description?: string;
  public?: boolean;
  collaborative: boolean;
  owner: SpotifyOwner;
  images: SpotifyImage[];
  tracks?: PlaylistTracksRef;
  type: string;
}

export interface SearchPlaylists {
  items?: SpotifyPlaylist[];
  total: number;
}

export interface SearchTracks {
  items?: SpotifyTrack[];
  total: number;
}

export interface SearchResult {
  tracks?: SearchTracks;
  artists?: SearchArtists;
  albums?: SearchAlbums;
  playlists?: SearchPlaylists;
}

export interface ShowEpisode {
  id: string;
  name: string;
  description?: string;
  duration_ms: number;
  explicit: boolean;
  release_date: string;
  images: SpotifyImage[];
  uri: string;
  type: string;
}

export interface ShowEpisodesPage {
  items: ShowEpisode[];
  total: number;
  offset: number;
  limit: number;
  next?: string;
}

export interface SpotifyPlaylists {
  items: SpotifyPlaylist[];
  total: number;
  offset: number;
  limit: number;
  next?: string;
}

export interface SpotifyShow {
  id: string;
  name: string;
  description: string;
  publisher: string;
  images: SpotifyImage[];
  total_episodes: number;
  explicit: boolean;
  type: string;
}

export interface SpotifyShowPage {
  items: SpotifyShow[];
  total: number;
  offset: number;
  limit: number;
  next?: string;
}

export interface SpotifyUserProfile {
  id: string;
  display_name?: string;
  email?: string;
  product?: string;
  country?: string;
  images: SpotifyImage[];
  followers?: Followers;
}

export interface TopArtists {
  items: SpotifyArtist[];
  total: number;
  offset: number;
  limit: number;
  next?: string;
}

export interface TopTracks {
  items: SpotifyTrack[];
  total: number;
  offset: number;
  limit: number;
  next?: string;
}
